 SELECT
    p.STRIP_NO ,
	P.THICK_CLASS ,
	P.TEMP_CLASS
	FROM
	SCC_ACT_FMSEG A,
	SCC_FMSTRIP P
	WHERE
	A.TOM <= (
		SELECT
		TOM
		FROM
		SCC_ACT_FMSEG ACT
		WHERE
		ACT.STRIP_NO = 'INPUT%%INPUT'
		AND ACT.SEG_NO = 1)
		AND A.STRIP_NO = P.STRIP_NO
		AND A.SEG_NO = 1
	ORDER BY
		A.TOM DESC
		FETCH FIRST 2 ROW ONLY