SELECT
	COUNT(*) DELTA_ROLL
FROM
	SCC_ACT_FMSEG A,
	SCC_POST_ROLLGAP P
WHERE
	A.SEG_NO = 1
	AND
	A.TOM <= (
	SELECT
		TOM
	FROM
		SCC_ACT_FMSEG ACT
	WHERE
		ACT.STRIP_NO = 'INPUT%%INPUT'
		AND ACT.SEG_NO = 1)
	AND A.TOM >= (
				SELECT
					A.TOM
				FROM
					SCC_ACT_FMSEG A,
					SCC_POST_ROLLGAP P
				WHERE
					A.SEG_NO = 1
					AND
				A.TOM <= (
					SELECT
						TOM
					FROM
						SCC_ACT_FMSEG ACT
					WHERE
						ACT.STRIP_NO = 'INPUT%%INPUT'
						AND ACT.SEG_NO = 1)
					AND A.STRIP_NO = P.STRIP_NO
					AND P.SEG_NO = 1
					AND P.STAND_NO = 7
					AND CORR_ZEROPOINT_USE = 0
				ORDER BY
					TOM DESC
			FETCH FIRST 1 ROW ONLY)
	AND A.STRIP_NO = P.STRIP_NO
	AND P.SEG_NO = 1
	AND P.STAND_NO = 7