    SELECT
	f.FM_TEMP - t.EXIT_TEMP LAST_TEMP_DELTA
	FROM
	SCC_ACT_FMSEG A,
	SCC_FMSTRIP P,
	SCC_ACT_FMSEG f,
	SCC_POST_TEMP t
	WHERE
	A.TOM < (
		SELECT
		TOM
		FROM
		SCC_ACT_FMSEG ACT
		WHERE
		ACT.STRIP_NO = 'INPUT%%INPUT'
		AND ACT.SEG_NO = 1)
		AND A.STRIP_NO = P.STRIP_NO
		AND A.SEG_NO = 1
		AND T.STRIP_NO = P.STRIP_NO
		AND T.SEG_NO = 1
		AND T.STAND_NO = 7
		AND F.SEG_NO =1
		AND F.STRIP_NO = T.STRIP_NO
	ORDER BY
		A.TOM DESC
		FETCH FIRST 1 ROW ONLY