SELECT
--------------------该块
	ACT.STRIP_NO
FROM
	AP.SCC_ACT_FMSEG AS ACT,
    AP.SCC_FMSTRIP AS SF
WHERE
    ACT.SEG_NO = 1
    AND ACT.STRIP_NO = SF.STRIP_NO
    AND SF.THICK_CLASS <= (
	SELECT
		THICK_CLASS + 1
	FROM
		AP.SCC_FMSTRIP FM
	WHERE
		FM.STRIP_NO = 'INPUT%%INPUT')
	AND SF.THICK_CLASS >= (
	SELECT
		THICK_CLASS - 1
	FROM
		AP.SCC_FMSTRIP FM
	WHERE
		FM.STRIP_NO = 'INPUT%%INPUT')
ORDER BY
	ACT.TOM DESC
