SELECT
	TIMESTAMPDIFF(2, CHAR(TIMESTAMP(TOM) - TIMESTAMP('2021-06-01 08:00:00'))) AS UNIX_TIME
FROM
	SCC_ACT_FMSEG
WHERE
	SEG_NO = 1 AND
	TOM < (
	SELECT
		TOM
	FROM
		SCC_ACT_FMSEG ACT
	WHERE
		ACT.STRIP_NO = 'INPUT%%INPUT'
		AND ACT.SEG_NO = 1)
ORDER BY UNIX_TIME DESC
FETCH FIRST 1 ROW ONLY